# Drupal 8 recipe
name: UniMOOC
recipe: drupal8
config:
  php: '7.1'
  via: nginx
  webroot: drupal
  drush: composer
# If using Ubuntu or possibly other systems and the Database service doesn't start correctly, uncomment the two lines below, enter "lando rebuild" in the command line then 
#  database:
#    type: mysql:5.7

  xdebug: true
